name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main # veya dağıtmak istediğiniz dal adı

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # Diğer gerekli parametreleri burada belirtin
          app_location: / # Uygulama dosyalarının konumunu burada belirtin
